version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "DioSamExample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9115tbwce1r"
s3_prefix = "DioSamExample"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
